# Generated by Django 2.1.3 on 2021-03-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
    ]
